### ISSUE TITLE
Accessibility: unlabeled buttons in localmonero with talkback

### ISSUE THREAD

**Issue by davidbtc2009** [AgoraDesk-LocalMonero/agoradesk-app-foss#105]
- [x] On the first screen the matrix and telegram buttons are unlabeled with talkback

- [x] After tapping "i want to buy" or "i want to sell" the back button at the top left only reads as "button"

- [x] On the login screen the "username" box only reads as "edit box" instead of "username". The password box is completely skipped in favor of the show/hide password eye icon that only reads as "button"

- [x] Once logged in on the setup pin screen the back button aylt the top left again only reads as "button" as does the backspace key to the right of "0"

- [x] Once the pin is set and you are taken to the market page, the notifications (top left), help (top right), down arrow (right of online buy), filter (right of the down arrow), the share (top right corner of each listing, square with right upward slanting arrow) are all read as "button"

- [x] When an ad is opened the back button (top left), tips "I" in a circle (top right), share (right of "about this ad, square with slanted right up pointed arrow), copy (right of "terms of trade with" user) are all labeled as "button".

- [x] Before "read more" the "..." Is a button that either shouldnt exist or be melded in with "read more"

- [x] When the tips screen is opened the "x"  (top right of the open box) reads as "button"

- [x] In the wallet tab the notifications button again only reads as "button"

- [x] In the trades tab the notification button (top left) and the down arrow (right of "all") read as "button"

- [x] The filter button (right of the down arrow) is not read at all

- [x] On the ads tab the same issues as on the trades tab apply (see above) and the "+" button reads as "button"

**Comment by sergdeus** [comment]
Hi!
Thank you for reporting.
Sorry, but I don't understand what you meant.
That there are no icons and text instead of them?
A screenshot would help to understand.

**Comment by davidbtc2009** [comment]
@sergdeus  Ah, im sorry. Talkback is a screen reader for those of us who are blind. So each thing displayed on screen is spoken to us. You can enable talkback in settings > Accessibility. Once done you can open the app and you will encounter the issues i listed.

**Comment by sergdeus** [comment]
Ou, got you.
Will be fixed with the next release.

**Comment by davidbtc2009** [comment]
@sergdeus many thanks

**Comment by davidbtc2009** [comment]
I unchecked the things i still se as issues

**Comment by sergdeus** [comment]
Thanks, I tried to check it by myself, but couldn't handle the controls.

**Comment by sergdeus** [comment]
Sorry, can't understand what kind of screen did you mean?

`When the tips screen is opened the "x" (top right of the open box) reads as "button"`

**Comment by davidbtc2009** [comment]
@sergdeus open an ad and tap the "i" in a circle (tip right, screenshot included below
![Screenshot_20221110-045335_LocalMonero](https://user-images.githubusercontent.com/67274571/201059598-93ddc469-c8df-4a70-9bf7-37c41bd4fc7f.png)

**Comment by sergdeus** [comment]
Thanks, fixed.
Can you please specify this

`Once the pin is set and you are taken to the market page, the notifications (top left), help (top right), down arrow (right of online buy), filter (right of the down arrow), the share (top right corner of each listing, square with right upward slanting arrow) are all read as "button"`

I checked all buttons and hadn't found what is wrong.

**Comment by davidbtc2009** [comment]
@sergdeus here are screenshots

![Screenshot_20221110-055053_LocalMonero](https://user-images.githubusercontent.com/67274571/201072654-7b40731c-cd2f-40b3-8bbc-eee53f7fdf82.png)
![Screenshot_20221110-055106_LocalMonero](https://user-images.githubusercontent.com/67274571/201072657-f03b6450-4981-47cc-9508-0c1864aa67c7.png)
![Screenshot_20221110-055118_LocalMonero](https://user-images.githubusercontent.com/67274571/201072659-1a01c0b2-35fb-4131-b24d-8da8f883059a.png)
![Screenshot_20221110-055130_LocalMonero_1](https://user-images.githubusercontent.com/67274571/201072660-0bf0e000-a4f6-4ca0-a774-cfdf43509c12.png)

**Comment by sergdeus** [comment]
Done, please check with a new release (I hope tomorrow)

**Comment by davidbtc2009** [comment]
@sergdeus when the new version comes out i will absolutely try it.

**Comment by davidbtc2009** [comment]
@sergdeus it is quite a bit better but not everything is perfect yet. Should i open a new issue with what remains and some new things i notice so as to have a fresh start or add more to this issue?

**Comment by sergdeus** [comment]
Hi! Thank you for checking - I think it is better to start a new issue, to keep it clear.

**Comment by davidbtc2009** [comment]
@sergdeus done. Issue #126
