### ISSUE TITLE
Fully remove firebase from foss version

### ISSUE THREAD

**Issue by dhammel** [AgoraDesk-LocalMonero/agoradesk-app-foss#111]
Hello,

When installing the latest foss version of local monero, It seems like it is indeed not using FCM. Although when inspecting the app, it appears that Firebase services, providers and receivers are present.

Can you remove those from the foss build? It would be required anyway to publish to fdroid.

**Comment by sergdeus** [comment]
Yes, you are right. We already did it.
The next releases will be without FCM.

**Comment by sergdeus** [comment]
@dhammel 
A small delay, we had a critical bug with iOS and hadn't time to change the ci.
The next release will have separated apks.

**Comment by dhammel** [comment]
@sergdeus Ok, will be looking forward to it.

Thanks
