### ISSUE TITLE
Accessibility, more things

### ISSUE THREAD

**Issue by davidbtc2009** [AgoraDesk-LocalMonero/agoradesk-app-foss#126]
Everything done below is with the talkback screen reader. Which can be enabled in the "Accessibility" section of android settings

- [x] The password box is completely skipped on the login screen. See the username box focuses in screenshot 1, the show/hide password focuses in screenshot 2 and the one time password (if enabled) focuses in screenshot 3.
![Screenshot_20221118-083931_LocalMonero](https://user-images.githubusercontent.com/67274571/202732453-8828492e-7dc3-46ec-9ac3-008ef7e605b2.png)
![Screenshot_20221118-083943_LocalMonero](https://user-images.githubusercontent.com/67274571/202732454-5d3360fd-5fe2-4506-b7bf-140d808f979b.png)
![Screenshot_20221118-083955_LocalMonero](https://user-images.githubusercontent.com/67274571/202732458-bc4ac4b0-16e2-40f9-bc05-95f67bb7b0f5.png)

- [x] In screenshot 3 above the "one time password (if enabled box only reads as "edit box"

- [x] In screenshots 4 and 5 the "forgot password flow is shown. I can access the back, email input box and send button, but have no idea what the text above the email box says as i cant access it
![Screenshot_20221118-084545_LocalMonero](https://user-images.githubusercontent.com/67274571/202740620-669fbdde-ca36-445e-95ee-c6710fcde179.png)
![Screenshot_20221118-084558_LocalMonero](https://user-images.githubusercontent.com/67274571/202740625-adca83e5-f6da-4c51-a57a-0e7a9f0b6ada.png)

- [x] In screenshots 6 and 7 the "setup pin screen now has the delete button labeled, however, there is an extra button that just reads "button after it that still deletes. Notice the focus on what is read as "delete" is slightly wider than that of "button"
![Screenshot_20221118-085634_LocalMonero](https://user-images.githubusercontent.com/67274571/202741088-c8694535-d7ce-4843-9985-f8fbcd25f00a.png)
![Screenshot_20221118-085646_LocalMonero](https://user-images.githubusercontent.com/67274571/202741091-e9f4d15e-eca6-466a-97c7-c990e21f3ee4.png)

- [x] In screenshots 8 and 9 the "notifications" and "help" have been focused. Just after each is another object that just says "button".
![Screenshot_20221118-104438_LocalMonero](https://user-images.githubusercontent.com/67274571/202745114-095de7f3-8698-4bb9-9c61-71e51e3072e3.png)
![Screenshot_20221118-091557_LocalMonero](https://user-images.githubusercontent.com/67274571/202741431-a1b05feb-37fd-4c90-bc49-59a30c7f7ada.png)
!

- [x] In screenshot 10 an ad is open. After the "information" button is another object just labeled "button" that also opens the information page
![Screenshot_20221118-091841_LocalMonero](https://user-images.githubusercontent.com/67274571/202746900-c44abd6e-1ae9-43bf-bb20-6ba393ac6407.png)

- [ ] In screenshot 11 the "copy" button is focused. Immediately after this copy button is another copy button.
![Screenshot_20221118-092142_LocalMonero](https://user-images.githubusercontent.com/67274571/202747486-7873d5fb-7003-436c-8dd0-70b1592ee18b.png)

- [ ] In screenshot 12 the ad terms are in focus, however the only thing spoken is "read more" or "show less" depending on if the terms are collapsed or expanded.
![Screenshot_20221118-092630_LocalMonero](https://user-images.githubusercontent.com/67274571/202747966-93228340-6678-4cd2-9530-7783916f4fa3.png)

- [x] In screenshot 13 the "show more" button is shown. This works as expected.
![Screenshot_20221118-092653_LocalMonero](https://user-images.githubusercontent.com/67274571/202748273-c9f5055d-1e15-47d7-8873-4486b0b79623.png)

- [x] In the "wallet" tab and the "trades" the notifications button has that extra "button" after it again (see screenshot 8 above)

- [x] In screenshot 14 the arrow next to "all ads" reads as "button"
![Screenshot_20221118-093658_LocalMonero](https://user-images.githubusercontent.com/67274571/202743740-bd4186b5-e166-4676-9fcb-f02743d686e6.png)

Edit: i found another one

- [x] in screenshots 15 and 16 a trade chat is displayed. Here the attach photo button (paperclip and send message button (up arrow in a circle) only read as "button"
- [ ] 
![Screenshot_20221120-165038_LocalMonero_1](https://user-images.githubusercontent.com/67274571/203041391-959aeb19-b08f-402f-b7d9-f6f18495de14.png)
![Screenshot_20221120-165055_LocalMonero_1](https://user-images.githubusercontent.com/67274571/203041445-46153754-af52-4bcc-bde6-7b95e3ba566d.png)

**Comment by sergdeus** [comment]
Outstanding job, thank you.
Will be done with the next release.

**Comment by davidbtc2009** [comment]
@sergdeus i found another one and added it to the bottom of the post

**Comment by sergdeus** [comment]
Thank you! Had some critical things to do. Next week will do this issue.

**Comment by sergdeus** [comment]
Hi!
About this issue
`The password box is completely skipped on the login screen. See the username box focuses in screenshot 1, the show/hide password focuses in screenshot 2 and the one-time password (if enabled) focuses in screenshot 3.`

I've tried accessibility mode with voice, and I should press this field and in this case, it works well.

How can I reproduce this issue?

**Comment by sergdeus** [comment]
> @sergdeus Odd. It is not working for me. I attempted tapping the box directly ans swiping right with one finger and could not access it.
> 
> Edit: is the coding different from the username box other than hiding the input? Because for me the username box is fine. I am on the version ending in .37 if that helps

Yes, the coding is different.
I've added an additional focus request for a password field.
Please check does it help or not.
I can't check, because I can tap into this field with the old code as well.

**Comment by davidbtc2009** [comment]
@sergdeus nope. It would require a new app version to test

**Comment by sergdeus** [comment]
Yes, we will make a release tomorrow.

**Comment by davidbtc2009** [comment]
@sergdeus. Okay, i will test it then

**Comment by davidbtc2009** [comment]
So, the thing with the one time password box is now fixed. The password box is still skipped so i have unvhecked it. The forgot password text is read, but the focus is wrong (see screenshot. It has the focus on the entire app and not the element itself. It looks like this, 
![Screenshot_20221201-122245_LocalMonero](https://user-images.githubusercontent.com/67274571/205119694-ae3a4250-7e7e-45c4-b9fe-4eb510441ef2.png)
When it should look more like this

**Comment by sergdeus** [comment]
> h the one time password box is now fixed. T

Ok., thank you.
I think I definitely should learn to test it by myself as well.
What is your Android version?

**Comment by davidbtc2009** [comment]
@sergdeus Android 11

**Comment by sergdeus** [comment]
I've figured out how to use this feature.
So, with the next update please check the Login, Sign up, and Reset password screens.
If they are ok I'll move further.

**Comment by davidbtc2009** [comment]
@sergdeus i will. Thanks for putting in the work. I know it can:t be easy dealing with this stuff

**Comment by davidbtc2009** [comment]
@sergdeus FANTASTIC! They work now. Login screen is fine, reset screen is fine. Only issue is that the "confirm password" box on the register screen only says "password" instead of "confirm password l" when using talkback. Otherwise perfect!

**Comment by sergdeus** [comment]
Great, thank you for testing.
In the next release, I'll finish all other issues.
For the new one - please open a separate thread.

**Comment by davidbtc2009** [comment]
@sergdeus will do
