### ISSUE TITLE
[BUG] Android: able to open trade chat without PIN

### ISSUE THREAD

**Issue by davidbtc2009** [AgoraDesk-LocalMonero/agoradesk-app-foss#131]
This is on the FOSS app but may affect others too. If you open the app and the foreground service message saying "LocalMonero Notification Service Checking for notifications. tap to read more" appears in the status bar. Then swipe the app away and get a trade chat you can tap the trade chat and talk with the other person without requiring the app PIN. If you try to exit the chat the PIN is required, but you shouldnt be able to open the chat at all without PIN first as it would contain sensative info.

**Comment by sergdeus** [comment]
Hi! Thank you for reporting this bug.
I've checked - this is a FOSS version bug.
Fixing.

**Comment by sergdeus** [comment]
Fixed, please check, new release is ready.
