### ISSUE TITLE
high battery drain

### ISSUE THREAD

**Issue by davidbtc2009** [AgoraDesk-LocalMonero/agoradesk-app-foss#133]
Localmonero FOSS drained my battery by ~25% in a 7 hour evening with no other apps running while i was asleep. I suspect this is because of the foreground service pinging the server to often to allow the phone to rest. This can be fixed by polling for notifications less often (say once every 15 minutes) or adding #104

**Comment by sergdeus** [comment]
Done, please check with the next release.
