### ISSUE TITLE
ad filter 2

### ISSUE THREAD

**Issue by Wjxfi** [AgoraDesk-LocalMonero/agoradesk-app-foss#136]
At the very beginning there should be ads with users who have been in the app very recently. at the very end there should be ads with sellers who haven't been in the app for a very long time.

**Comment by LocalMonero** [comment]
> At the very beginning there should be ads with users who have been in the app very recently. at the very end there should be ads with sellers who haven't been in the app for a very long time.

That's exactly how it works.

**Comment by LocalMonero** [comment]
You need to have 3 confirmed feedbacks before you start being sorted on activity/price. See #135

**Comment by LocalMonero** [comment]
Please contact https://t.me/ALEX_LOCALMONERO_AGORADESK on Telegram or @alex:agoradesk.com on matrix.
