### ISSUE TITLE
Accessibility: minor issues

### ISSUE THREAD

**Issue by davidbtc2009** [AgoraDesk-LocalMonero/agoradesk-app-foss#149]
Everything done below was done with the Talkback screen reader which can be enabled from settings > accessibility on Android 11. These are the last few i found easily but some more may crop up from time to time in less well tested parts of the app.

- [x] The entire box is focused and read aloud instead of focusing on "disclaimer" and the below text as separate elements. See screenshot 1
![Screenshot_20221212-121902_LocalMonero](https://user-images.githubusercontent.com/67274571/207119369-ea4807f7-3207-4a32-89bf-05e0181bb103.png)

- [x] On the create account screen the "confirm password" edit box reads as "password" instead of "confirm password" see screenshot 2
![Screenshot_20221212-122055_LocalMonero](https://user-images.githubusercontent.com/67274571/207119612-3d93b9e8-b409-4147-acb1-45b80da51e9a.png)

- [x] I am unable to access the terms of service link see screenshot 3
![Screenshot_20221212-122122_LocalMonero](https://user-images.githubusercontent.com/67274571/207120038-f7e2d021-0051-412e-81df-f6560f08d993.png)

- [x] The notifications button reads as "notifications notifications notifications" instead of "notifications". See screenshot 4.
![Screenshot_20221212-122502_LocalMonero](https://user-images.githubusercontent.com/67274571/207120289-11ca7348-1ef5-4ac6-b2ec-59fa04c6a97a.png)

- [x] When an ad is open and the tips button is pressed, the entire window is focused and reads "tips close button" but it is not actually a button (and should not be) see screenshot 5. the first element focused should be the word "tips".
![Screenshot_20221212-122811_LocalMonero](https://user-images.githubusercontent.com/67274571/207120519-ab10b05f-5124-41c8-8b1c-0cd5c9c82358.png)

- [x] When an ad is open there are 2 instances of the "copy button" see screenshot 6
![Screenshot_20221212-123219_LocalMonero](https://user-images.githubusercontent.com/67274571/207120709-3dc7b875-064f-4334-94bc-2e66b478dd38.png)

- [x] On the trades tab the down arrow next to all reads as "button". See screenshot 7
![Screenshot_20221212-123616_LocalMonero](https://user-images.githubusercontent.com/67274571/207120891-0d67230d-e6d6-4ced-89cd-f773e9beef72.png)

**Comment by sergdeus** [comment]
Thank you!
If you would like we can add you as our accessibility tester to the readme file.

**Comment by davidbtc2009** [comment]
That would be fine. Though i would prefer the use of my screen name "shortwavesurfer2009". I have that github account, go by that on LM, Reddit, and Mastodon

**Comment by sergdeus** [comment]
Here you are
https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss

**Comment by davidbtc2009** [comment]
@sergdeus thanks, i really appreciate it.

**Comment by davidbtc2009** [comment]
Thanks. This fixes the issues.
