### ISSUE TITLE
Accessibility, A Few More Found

### ISSUE THREAD

**Issue by davidbtc2009** [AgoraDesk-LocalMonero/agoradesk-app-foss#157]
All these issues are found when using the Talkback screen reader on Android which can be enabled in system settings > Accessibility.

- [x] the mark as read and close buttons are not labeled when the notifications list is open. See screenshots 1 and 2 
![Screenshot_20221230-154028_LocalMonero_1_1](https://user-images.githubusercontent.com/67274571/210110527-68a6889a-a06b-4ba2-9e69-21e0f237fb7b.png)
![Screenshot_20221230-154016_LocalMonero_1_1](https://user-images.githubusercontent.com/67274571/210110528-75e867fa-aa23-4dea-be2c-5fa2881891fd.png)

- [x] when opening the filter screen, the arrow buttons next to payment method, currency, and country are read as "button". See screenshots 3, 4, and 5
- 
![Screenshot_20221230-154844_LocalMonero](https://user-images.githubusercontent.com/67274571/210110775-fd66561b-914b-4dfe-a504-198b04ca9230.png)
![Screenshot_20221230-154828_LocalMonero](https://user-images.githubusercontent.com/67274571/210110778-e8dc8c1d-d115-4e4d-82bb-e884fc972db7.png)
![Screenshot_20221230-154813_LocalMonero](https://user-images.githubusercontent.com/67274571/210110780-3f54762f-331c-486b-b863-45ef0f064831.png)

- [ ] when opening the box to choose a payment method, currency, or country the edit box cant be used. See screenshots 6, 7, and 8.
![Screenshot_20221230-155652_LocalMonero_1](https://user-images.githubusercontent.com/67274571/210111219-d51b549d-4d9f-4849-a194-f25ab1e85ea3.png)
![Screenshot_20221230-155659_LocalMonero_1](https://user-images.githubusercontent.com/67274571/210111221-e369a121-e29e-405c-82ff-f70842f69d11.png)
![Screenshot_20221230-155704_LocalMonero_1](https://user-images.githubusercontent.com/67274571/210111222-2e2f2c6c-9f27-41a5-a9be-1ffe9887debe.png)

Edit: missed one.
- [x] the button to make the ad visible on the service focuses but says nothing. See screenshot 9. My suggestion is for it to say "Enable Ad" when disabled as pictured and say "Disable Ad" when the ad is enabled.
![Screenshot_20221230-160559_LocalMonero_1](https://user-images.githubusercontent.com/67274571/210111802-bac34433-4773-4f36-8f46-438f8f8eaeef.png)

**Comment by sergdeus** [comment]
Hi,
all fixed, except this one
`when opening the box to choose a payment method, currency, or country the edit box cant be used. See screenshots 6, 7, and 8.`

I should rewrite the plugin that creates these windows, I will do it in a couple of weeks.

For new bugs please create new issues, I will fix them quickly.

**Comment by shortwavesurfer2009** [comment]
@sergdeus will do, thanks.

**Comment by shortwavesurfer2009** [comment]
@sergdeus  F-droid finally updated me to the latest version and the ones you marked fixed are indeed fine.

**Comment by shortwavesurfer2009** [comment]
Any update on the edit boxes?

**Comment by sergdeus** [comment]
Sorry for disappearing, had a critical bug and some urgent tasks.
Will try to do it this week.
