### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by recanman** [AgoraDesk-LocalMonero/agoradesk-app-foss#160]
In the Translation section, the following is stated:

The source of truth for the translation files is .json language files for web-version. https://github.com/AgoraDesk-LocalMonero/translation

Upon visiting the link provided, https://github.com/AgoraDesk-LocalMonero/translation, I get a 404. Maybe the Weblate instance used for translation can be used to view what is translated?

**Comment by LocalMonero** [comment]
Removed the section since we moved to a non-public Weblate-based translation setup.
