### ISSUE TITLE
Save default country and currency in settings

### ISSUE THREAD

**Issue by trymeouteh** [AgoraDesk-LocalMonero/agoradesk-app-foss#170]
Please have a setting which will save the users default country and currency. This way when logging into another device and go to the market tab, it will display the trades from their country and their currency by default.

**Comment by LocalMonero** [comment]
You can already change it, go to Account -> Settings -> Country

**Comment by trymeouteh** [comment]
There is not currency setting and these settings do not get saved when I log into the websites on my desktop.

**Comment by LocalMonero** [comment]
The currency is set along with the country, e.g. if you select Australia you get AUD.

We don't save the settings to the account to ensure maximum privacy.
