### ISSUE TITLE
More offer sorting options

### ISSUE THREAD

**Issue by trymeouteh** [AgoraDesk-LocalMonero/agoradesk-app-foss#171]
On the website, you can choose any offer type such as cash, paypal, e-transfer, etc. On mobile you are limited to online and local offers. Please add more sorting options for offers on mobile.

**Comment by LocalMonero** [comment]
You *can* select payment methods on the app as well. Could you show us a screenshot of where you think this option is missing, please?

**Comment by trymeouteh** [comment]
I found it now in the filter settings above the currency setting.
