### ISSUE TITLE
Gold, Silver, Goldbacks, Silverbacks as offer options

### ISSUE THREAD

**Issue by trymeouteh** [AgoraDesk-LocalMonero/agoradesk-app-foss#173]
Please add gold and silver as trade options for BTC and XMR. Weather it is gold coins, gold bars, silver coins, silver bars, etc

And please also consider adding Goldbacks (and the new Silverbacks) as a trade option too. Goldbacks are growing in popularity.

https://goldback.com/

**Comment by LocalMonero** [comment]
Gold and silver are already available, check the currency selector for XAU and XAG. Goldbacks can be listed under that category too.

**Comment by trymeouteh** [comment]
To trade Monero and Bitcoin to/from Gold, Silver, Goldbacks and Silverbacks. Just like you can have XMR to/from Cash by mail trades but instead you can have XMR to/from Silver or XMR to/from Goldback trades.

**Comment by LocalMonero** [comment]
It's already available: https://localmonero.co/sell-monero-with-xau

**Comment by trymeouteh** [comment]
> It's already available: https://localmonero.co/sell-monero-with-xau

Personally I view this filter as selling Monero using gold as the currency to measure the transaction. The cash by mail under this category I would view as selling my Monero for cash (the currency to be determine in the ad weather it is USD, CAD, EUR) but the transaction is measured in gold, not Monero, not fiat dollars. 

Another example would be an add selling Monero using Bitcoin as the currency and the offer is cash by mail. I would view this ad as selling my Monero for cash (the currency to be determine in the ad weather it is USD, CAD, EUR) but the transaction is measured in bitcoin, not Monero, not fiat dollars.

I know it is more offer options, but I view cash by mail as fiat cash by mail. To have a "Gold", "Silver", "Gold & Silver", "Goldbacks", "Silverbacks", "Goldbacks & Silverback" option will go a long way for clarity in my opinion.
