### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [AgoraDesk-LocalMonero/agoradesk-app-foss#198]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3827654062#L1740

/LE: disabled: https://gitlab.com/fdroid/fdroiddata/-/commit/0dfd5641b55874eb1db0b9d892925780018be1d1

**Comment by licaon-kter** [comment]
But a question still stands, why is there no `.gitmodules` file in the repo?

**Comment by sergdeus** [comment]
Yep.

**Comment by sergdeus** [comment]
> Oddly enough these built fine on the main build server (and published already) yet in the past failed in the CI. Sorry for the noise. [Reverted](https://gitlab.com/fdroid/fdroiddata/-/commit/14784737535abc6481b7305bd32f2b6285b8bb60)

I also noticed this, but I don't know the reason.


>

**Comment by licaon-kter** [comment]
@sergdeus can you bump flutter submodule version? https://monitor.f-droid.org/builds/log/co.localmonero.app/1001#site-footer

**Comment by sergdeus** [comment]
Hey @licaon-kter 
I'm not sure that I did it correctly, bumped.

**Comment by licaon-kter** [comment]
Thanks

**Comment by sergdeus** [comment]
Yes, thank you!
I will do this with the next version. There were no critical updates.
