### ISSUE TITLE
Add timer to PIN & logout after 25 attempts.

### ISSUE THREAD

**Issue by sergdeus** [AgoraDesk-LocalMonero/agoradesk-app-foss#201]

**Comment by shortwavesurfer2009** [comment]
25 attempts seems a bit high. Why not 5 or 10 instead?

**Comment by sergdeus** [comment]
As it is made in the native Android:
1. After every 5 attempts, it will be blocked for 30 seconds.
2. After a total 25 attempts app will be forced to log out.
