### ISSUE TITLE
Address book data encrypted?

### ISSUE THREAD

**Issue by trymeouteh** [AgoraDesk-LocalMonero/agoradesk-app-foss#206]
Is the address book data stored on the server with E2EE, were only the user can decrypt the data?

**Comment by LocalMonero** [comment]
Not at the moment, we'll consider switching to E2EE for it, but it's not as simple because our website needs to be able to work without JavaScript, and you can't do E2EE in the browser without JavaScript.

**Comment by trymeouteh** [comment]
Having no JS option is nice for those who disable JS on their browsers.

I would like to suggest two options:

1. Release a desktop client (Since the mobile app is made with dart/flutter and could be likely compiled for desktop) and then having the website a JS only website
2. Keep the no JS option on the website but with feature limitations, which will include no address book and using other features that require E2EE.
3. Both, have a desktop client and limited feature on the web client when there is no JS. If users who want all of the features without JS on desktop will have to use the desktop client.

I think option 2 is best personally.
