### ISSUE TITLE
Agoradesk.foss Android Login Fail

### ISSUE THREAD

**Issue by kycfree1** [AgoraDesk-LocalMonero/agoradesk-app-foss#216]
Version: Agoradesk 1.0.70 Foss.
Hardware: Pixel 7 Pro / GrapheneOS.
Installed from: GitHub Repo.

After installation, attempting to login is failing.

After entering login credentials I am forward to a captcha verification screen where you are prompted to slide the jigsaw piece for human verification.
Completing this forwards me to what looks like the web version of Agoradesk for 2 or 3 seconds before I am returned again to the human verification screen. I am never asked to login again, however, this verification process is on an infinite loop, with me unable to access the application interface itself.

**Comment by luphoria** [comment]
+1

**Comment by sergdeus** [comment]
Hi!
Yes, this is a weird bug. Fixed. Making a release right now.
Thank you for submitting the bug.

**Comment by luphoria** [comment]
works on my device
