### ISSUE TITLE
"Must be less X.XX USD" text

### ISSUE THREAD

**Issue by luphoria** [AgoraDesk-LocalMonero/agoradesk-app-foss#235]
I recently tried to use AgoraDesk to purchase XMR on [this offer](https://localmonero.co/ad/buy-monero-square-cash-united-states-of-america/992af6b5-2997-468f-aaf6-b52997168f19) (a range of 40-200 USD). If my offer is below $40, it gives the proper error, but if it's above $200, it reads `Must be less 0.00 USD`. (The error should read `
This trader doesn't have enough balance to start a trade for this amount.`)

But weirder - even in the 40-200 range, I get the same error: `Must be less 0.00 USD`. 

LocalMonero Web gives a different error for this scenario: `This trader requires lower transaction amount for the first trade with him. Please check the trade details below.`

So, a few takeaways:
 - The message `Must be less X.XX Y` should be [...]`less than X.XX`[...]. 
  - On mobile, there should be the error `This trader requires lower transaction amount for the first trade with him. Please check the trade details below.`

**Comment by sergdeus** [comment]
Hi!
Thank you for catching it.
Will be fixed with the new release.
