### ISSUE TITLE
I am unable to save an ad after editing the price, or to mark all conversations as read (Android)

### ISSUE THREAD

**Issue by sergdeus** [AgoraDesk-LocalMonero/agoradesk-app-foss#242]

**Comment by augrLpWo** [comment]
+1. Only ad editing option I saw working was visibility (which only worked if you were in the "Edit ad" menu)

**Comment by sergdeus** [comment]
What app version are you using? (You can check the version at the bottom of the Account screen).
This should be fixed in v.1.1.10.
