### ISSUE TITLE
disputes with local trades

### ISSUE THREAD

**Issue by sergdeus** [AgoraDesk-LocalMonero/agoradesk-app-foss#255]
was in the middle of a local trade and the buyer didn't show up, so I needed to file a dispute.  I tried to use the "Start a Dispute" option from the dropdown menu.  The "confirm dispute" dialog opened, but when I tapped "confirm" nothing happened.

**Comment by vladimir-bruteforce** [comment]
Hello. you have to wait up to 24 working shours for an admin to show up
