### ISSUE TITLE
Dispute trade button not working

### ISSUE THREAD

**Issue by RockyRoad65** [AgoraDesk-LocalMonero/agoradesk-app-foss#263]
It doesn't matter if I try holding down on it or double tapping it or anything but the dispute trade button doesn't work for some reason. I'm using the android version from F-droid.

https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/assets/108962763/19a9b71c-d578-4969-bc57-63e884d8e838

**Comment by sergdeus** [comment]
Hi!
I can see that the trade has been canceled. 
I will check why there was the button for the dispute - you can't dispute such trades.
But you can ask support to handle the case https://localmonero.co/faq
