### ISSUE TITLE
can't paste passwords in the app (Graphene phones)

### ISSUE THREAD

**Issue by sergdeus** [AgoraDesk-LocalMonero/agoradesk-app-foss#264]

**Comment by sergdeus** [comment]
Hey Mark,

Thank you! We will push an updated version on Thursday. I'll let you know here.

**Comment by sergdeus** [comment]
Hi!
Can you please test, the update is online on Play, AppStore, Github.

**Comment by markisoke** [comment]
Yes, it's working as expected now.
