### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by trymeouteh** [AgoraDesk-LocalMonero/agoradesk-app-foss#265]
A new section to the site were users can sell items for Monero or Bitcoin.

Just like Facebook Marketplace but without more privacy.

Sellers can list physical goods which can be shipped or digitial goods which can be sent over email, URL or a messaging app.

If abuse is a problem, add a $5 BTC or XMR fee to gain access listing items to sell on the marketplace.

Having a marketplace section on the website and the app will be great. Especially since the app allows you to recieve notifications on messages and trades.

**Comment by LocalMonero** [comment]
Thanks for the suggestion. We may consider doing this in the future.
