### ISSUE TITLE
Market Tab keeps reseting my selected payment and coin option

### ISSUE THREAD

**Issue by sergdeus** [AgoraDesk-LocalMonero/agoradesk-app-foss#276]
There is a Bug in the Android version of the app. The Market Tab keeps reseting my selected payment and coin option. And also recently also my country.

So every time I select the Market. I first have to go in to Settings to select COUNTRY, then select Payment option PAYMENT

**Comment by LocalMonero** [comment]
![image](https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/assets/31570671/23964cc5-a67f-4604-b94e-f2ee3f7ba4c8)

Bug report OS details
