### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by caomadan** [AgoraDesk-LocalMonero/agoradesk-app-foss#292]
When I use the APP to connect to the proxy, I can connect without user and password authentication, but cannot connect with user and password authentication. please help me. I use socks server[https://github.com/ginuerzh/gost](url).Thanks.

**Comment by sergdeus** [comment]
Hello!
Did you use the SOCKS5 protocol to create a proxy?

**Comment by caomadan** [comment]
Yes.

**Comment by sergdeus** [comment]
Can you send me a PM with proxy credentials to test? Otherwise, it is hard to catch the issue.

**Comment by caomadan** [comment]
socks5://user:pass@142.171.48.90:1088

**Comment by sergdeus** [comment]
Thank you.
Fixed, will be deployed today.
