### ISSUE TITLE
Receipt and Settlement Proof are both borked

### ISSUE THREAD

**Issue by 48-mq** [AgoraDesk-LocalMonero/agoradesk-app-foss#293]
Here's an example of a receipt: 
![Screenshot_20240428-135215](https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/assets/145857730/84d10d4d-dcfd-49af-9bd7-bfd9184d2098)

Here's an example of a settlement proof: 
![Screenshot_20240428-135232](https://github.com/AgoraDesk-LocalMonero/agoradesk-app-foss/assets/145857730/23a50547-fc0d-4907-ad1a-f7527e1d511c)

**Comment by sergdeus** [comment]
Hi!
Thank you for pointing that out.
Fixed.
Also added a button to share the receipt.

**Comment by 48-mq** [comment]
Tested and confirmed - thank you for the quick fix @sergdeus !
