### ISSUE TITLE
*Feature Request* Update alert/link on update.

### ISSUE THREAD

**Issue by ghost** [AgoraDesk-LocalMonero/agoradesk-app-foss#70]
For those using the APK download application a clear in-app alert that an updated version of the application is available would be beneficial when using an outdated version of the app.

A link to the latest upgradable version would be very useful.

**Comment by LocalMonero** [comment]
How about a self-updater for those using the APK build?

**Comment by awaik** [comment]
Hi!
I think next week it will be ready.

**Comment by sergdeus** [comment]
Hi!
Added it to the backlog - in 1-2 releases it will be ready.
